education:
- school: "Stevens Institute of Technology"
  graduationDate: "May 2018"
  degree: "M.S. in Cybersecurity"
  gpa: 3.67
  roles: []
- school: "Stevens Institute of Technology"
  graduationDate: "May 2017"
  degree: "B.S. in Computer Science and Mathematics Minor"
  gpa: 3.40
  roles:
  - title: "Teaching Assistant"
    startDate: "Feb 2015"
    endDate: "Dec 2017"
    description: "Algorithms, Concurrent Prog., Operating Systems, Team Prog. & Problem Solving"

experience:
- company: "IBM"
  roles:
  - title: Software Engineer - TradeLens
    startDate: August 2018
    description:
    - Designed and created a generic, role-based, hierarchical access policy
      evaluation service with Node.js and TypeScript for enforcing complex data
      access rules within TradeLens.
    - Worked with offering managers from Maersk and IBM to implement the
      shipment tracking feature within the TradeLens's event processing
      services using Java, Kafka, and Cloudant (CouchDB).
    - Built a service in Java which uses Cloudant to manage notification
      preferences and transmits notifications to end users via Twilio and
      SendGrid based on events issued by other services.
    - Helped to develop an ETL pipeline for TradeLens using Kafka, Apache Avro,
      Apache Spark SQL, and IBM Cloud Object Storage, which enables clients to
      perform analytics on and gather insights from large datasets of shipment
      and container events from various ocean carriers and freight forwarders.
    - Implemented various UI features in TradeLens's angular application.
    - Assisted in coordinating the deployment of various services throughout
      TradeLens to Kubernetes using Helm, Argo, Skaffold, and other tools.
    - Gained significant knowledge of EDIFACT, UN/CEFACT, and various norms and
      procedures of the international shipping industry.

  - title: "Software Engineering Intern - Extreme Blue"
    startDate: "May"
    endDate: "August 2017"
    description:
    - Architected and implemented an identity management solution that uses a combination of biometrics and other factors to securely authenticate individuals.
    - Created and delivered a pitch to over 50 executives at IBM's corporate headquarters in Armonk, NY.

- company: "iCIMS"
  roles:
  - title: "Software Developer Intern"
    startDate: "June"
    endDate: "August 2015"
    description:
    - Designed and implemented a system to automate merges, saving each developer an average of 4 hours/week.
    - Created a user-friendly web interface for the system using EmberJS and Material Design Lite.

  - title: "Software Development Engineer in Test (SDET) Intern"
    startDate: "June"
    endDate: "August 2014"
    description:
    - Implemented a system which aligns automation tests, unit tests, and QA tests within a test case management suite, saving QA technicians hours of manually entering test case information.

projects:
- name: TaylorFit
  description: |
    Worked closely with a client and 3 other students to build an isomorphic
    web app for analyzing data using multivariate polynomial regression. All
    processing is done client-side using WebWorkers to distribute complex
    calculations.

- name: SemNet
  description: |
    Created a python program which models entity relationships by parsing
    natural lanaguage and trained it on a subset of Wikipedia's "simple
    english" pages.
